// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqEG3V4VNNo39Fsm3F1NEHX1divrNtHGg',
    appId: '1:1078863273569:web:cd7b2571e499ba4564d420',
    messagingSenderId: '1078863273569',
    projectId: 'dating-app-e29f0',
    authDomain: 'dating-app-e29f0.firebaseapp.com',
    storageBucket: 'dating-app-e29f0.firebasestorage.app',
    measurementId: 'G-6JB3K9HCSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5CTARUIbyiDxsCeG2tXtcWO9sN_TlaqY',
    appId: '1:1078863273569:android:62b33353b452b22464d420',
    messagingSenderId: '1078863273569',
    projectId: 'dating-app-e29f0',
    storageBucket: 'dating-app-e29f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_WWVmuV1eo7aVrvEatP48dXYAuHul4jA',
    appId: '1:1078863273569:ios:871dd0216a85c36a64d420',
    messagingSenderId: '1078863273569',
    projectId: 'dating-app-e29f0',
    storageBucket: 'dating-app-e29f0.firebasestorage.app',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_WWVmuV1eo7aVrvEatP48dXYAuHul4jA',
    appId: '1:1078863273569:ios:871dd0216a85c36a64d420',
    messagingSenderId: '1078863273569',
    projectId: 'dating-app-e29f0',
    storageBucket: 'dating-app-e29f0.firebasestorage.app',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqEG3V4VNNo39Fsm3F1NEHX1divrNtHGg',
    appId: '1:1078863273569:web:fed7cf46755a19c364d420',
    messagingSenderId: '1078863273569',
    projectId: 'dating-app-e29f0',
    authDomain: 'dating-app-e29f0.firebaseapp.com',
    storageBucket: 'dating-app-e29f0.firebasestorage.app',
    measurementId: 'G-XJB15ZM48R',
  );
}
